research_task:
  description: >
    Conduct thorough research about {topic} based on the audience level {audience_level}.
    Make sure you find any interesting and relevant information given the current year is 2024.
  expected_output: >
    A thorough research report on {topic} with relevant information that can inspire educational content afterwards aimed at {audience_level}. The research report
    should also include references to the sources you used to create the content.
  agent: researcher

planning_task:
  description: >
    Review the content you received and come up with a plan for an amazing and comprehensive educational content piece that is aimed at {audience_level}.
    The plan should be highly detailed and comprehesive. 
  expected_output: >
    A detailed plan for an educational content piece that is aimed at {audience_level}. 
    The plan shoudl be a series of sections, each section with a subtitle, high level goal, why it's important, and sources referenced.
  agent: planner
