[theme]
base = "light"
primaryColor = "#250E36"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F2F2F2"
textColor = "#000000"
font = "sans serif"

[global]
# If True, will show a warning when you run a Streamlit-enabled script
# via "python my_script.py".
# Default: true
showWarningOnDirectExecution = false

[browser]
gatherUsageStats = false
