yahoo_finance_research_task:
  description: >
    Perform web scraping of Yahoo Finance News
    to gather the most relevant articles about the specified company
    and store them for review.
  expected_output: >
    A list of the file paths where the retrieved article texts have been saved.
  agent: yahoo_finance_researcher