services:
  main-agent:
    build:
      context: ./agents
      dockerfile: Dockerfile
    
    models:
      qwen3:
        endpoint_var: MODEL_RUNNER_URL
        model_var: MODEL_RUNNER_MODEL

    ports:
      - 8000:8000
    environment:
      PORT: 8000
      # --------------------------------------
      # SambaNova Agent configuration
      # --------------------------------------
      SAMBANOVA_BASE_URL: ${SAMBANOVA_BASE_URL}
      SAMBANOVA_CHAT_MODEL: ${SAMBANOVA_CHAT_MODEL}
      SAMBANOVA_API_KEY: ${SAMBANOVA_API_KEY}
      SAMBANOVA_AGENT_NAME: sambanova_agent
      SAMBANOVA_AGENT_DESCRIPTION: Main assistant and project manager coordinator
      SAMBANOVA_AGENT_INSTRUCTION: |
        You are SambaNova. All your answers MUST start with "SAMBANOVA_AGENT SPEAKING:".
        You are a project manager expert, your task is to extract information from any source of data (image, text)
        to describe as a programming project so the expert can create the code for it. Remember don't create code on your own
        The expert is developer.
        - If the user specifically wants to speak with developer, route to the developer_agent. 

      # --------------------------------------
      # Reviewer Agent Configuration
      # --------------------------------------
      
      DEVELOPER_AGENT_NAME: developer_agent
      DEVELOPER_AGENT_DESCRIPTION: Useful agent for general programming tasks
      DEVELOPER_AGENT_INSTRUCTION: |
        You are developer. All your answers MUST start with "REVIEWER SPEAKING:".
        Review the project manager information and create the code needed to complete the project.
        Always create the code given the information provided

        ### IMPORTANT:
        1. **No Parent Agent Routing:** Do not route back to the parent agent unless the user explicitly requests it.
        2. If the user specifically wants to speak with main, route to the sambanova_agent. 

models:
  qwen3:
    model: ai/qwen3:8B-Q4_0
