yfinance_stock_analysis:
  description: >
    Conduct a thorough financial investigation into the user’s query,
    emphasizing recent developments, notable trends,
    given that the current year is 2025 and the current month is February.
    Ensure your findings reflect the most up-to-date market conditions.
  expected_output: >
    Provide the list of the two file paths where your analyis is stored.
  agent: yfinance_stock_analyst