# sorting_task:
#   description: >
#     Determine which financial data sources to use for the user query.
#   expected_output:  >
#     A structured output.
#   agent: sorting_hat

extraction_task:
  description: >
    From the user query, identify and extract relevant information
    regarding the company, year, and any other required details.
    Then, produce a simplified version of the query
    that removes references to SEC Edgar Filings or other sources, making it more general.
  expected_output: >
    • A structured output with the extracted data.  
    • A simplified user query with no mention of SEC Edgar Filings.
  agent: extractor